{{- if and .Values.persistence.enabled .Values.ai.enabled }}
{{- $storageClassName := ternary .Values.persistence.storageClassName .Values.ai.persistence.storageClassName (empty .Values.ai.persistence.storageClassName) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.fullname" . }}-ai-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.ai.persistence.cacheSize }}
  storageClassName: "{{ $storageClassName }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.fullname" . }}-ai-config
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.ai.persistence.configSize }}
  storageClassName: "{{ $storageClassName }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.fullname" . }}-ai-caching
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.ai.persistence.cacheSize }}
  storageClassName: "{{ $storageClassName }}"
{{/* TODO
{{- if and .Values.persistence.upload.enabled (empty (.Values.persistence.upload.existingClaim).name) }}
{{- end }}
*/}}
{{- end }}
